//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace serniaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class japaneseHistory
    {
        public int idx { get; set; }
        public string title { get; set; }
        public string text { get; set; }
    }
}
