//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace serniaMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class serniaDBEntities : DbContext
    {
        public serniaDBEntities()
            : base("name=serniaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<devHistory> devHistory { get; set; }
        public virtual DbSet<japaneseHistory> japaneseHistory { get; set; }
        public virtual DbSet<japaneseMemo> japaneseMemo { get; set; }
        public virtual DbSet<serniaHistory> serniaHistory { get; set; }
    
        public virtual ObjectResult<devHistory> devHistoryList(Nullable<int> pAGE, Nullable<int> pAGESIZE, ObjectParameter tOTALPAGE)
        {
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<devHistory>("devHistoryList", pAGEParameter, pAGESIZEParameter, tOTALPAGE);
        }
    
        public virtual ObjectResult<devHistory> devHistoryList(Nullable<int> pAGE, Nullable<int> pAGESIZE, ObjectParameter tOTALPAGE, MergeOption mergeOption)
        {
            var pAGEParameter = pAGE.HasValue ?
                new ObjectParameter("PAGE", pAGE) :
                new ObjectParameter("PAGE", typeof(int));
    
            var pAGESIZEParameter = pAGESIZE.HasValue ?
                new ObjectParameter("PAGESIZE", pAGESIZE) :
                new ObjectParameter("PAGESIZE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<devHistory>("devHistoryList", mergeOption, pAGEParameter, pAGESIZEParameter, tOTALPAGE);
        }
    }
}
